import { Configuration, OpenAIApi } from "openai-edge";
import { OpenAIStream, StreamingTextResponse } from "ai";

const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

console.log("API key set!");
export const runtime = "edge";

const medicalKeywords = [
  "medicament",
  "tratament",
  "boală",
  "simptom",
  "doctor",
  "farmacie",
  "supliment",
  "sănătate",
  "diagnostic",
  "terapie",
  "consultație",
  "rețetă",
  "vaccin",
  "imunizare",
  "antibiotic",
  "analgezic",
  "antiinflamator",
  "antiseptic",
  "antihistaminic",
  "anestezie",
  "chirurgie",
  "oncologie",
  "radiografie",
  "ecografie",
  "tomografie",
  "RMN",
  "dializă",
  "transplant",
  "cardiologie",
  "neurologie",
  "dermatologie",
  "oftalmologie",
  "gastroenterologie",
  "endocrinologie",
  "psihiatrie",
  "psihologie",
  "pediatrie",
  "geriatrie",
  "ginecologie",
  "obstetrică",
  "urologie",
  "nefrologie",
  "hepatologie",
  "pneumologie",
  "reumatologie",
  "hematologie",
  "infecție",
  "virus",
  "bacterie",
  "fung",
  "parazit",
  "epidemie",
  "pandemie",
  "alergie",
  "intoleranță",
  "gluten",
  "lactoză",
  "nutriție",
  "dietă",
  "metabolism",
  "vitamină",
  "minerale",
  "probiotice",
  "enzime",
  "hidroterapie",
  "fizioterapie",
  "kinetoterapie",
  "acupunctură",
  "homeopatie",
  "fitoterapie",
  "aromaterapie",
  "masaj",
  "relaxare",
  "hipertensiune",
  "diabet",
  "colesterol",
  "trigliceride",
  "anemie",
  "leucemie",
  "trombocite",
  "plasmă",
  "insulină",
  "glucoză",
  "glucagon",
  "hormon",
  "testosteron",
  "estrogen",
  "progesteron",
  "tiroidă",
  "adrenalină",
  "cortizol",
  "serotonină",
  "dopamină",
  "imunitate",
  "autoimun",
  "inflamație",
  "artrită",
  "astm",
  "bronșită",
  "pneumonie",
  "sinuzită",
  "alzheimer",
  "parkinson",
  "epilepsie",
  "scleroză",
  "tumoră",
  "cancer",
  "metastază",
  "biopsie",
  "citostatice",
  "imunoterapie",
  "radioterapie",
  "chemoterapie",
  "rehabilitare",
  "recuperare",
  "plagă",
  "fractură",
  "luxație",
  "entorsă",
  "contuzie",
  "hemoragie",
  "coagulare",
  "transfuzie",
  "venă",
  "arteră",
  "capilar",
  "anestezic",
  "analgezic",
  "sedativ",
  "hipnotic",
  "tranchilizant",
  "antidepresiv",
  "antiepileptic",
  "antipsihotic",
  "antipiretic",
  "laxativ",
  "antidiabetic",
  "antifungic",
  "antiviral",
  "anticorpi",
  "imunoglobulină",
  "ser",
  "vaccinare",
  "profilaxie",
  "igienă",
  "sterilizare",
  "dezinfecție",
  "paliativ",
  "ambulatoriu",
  "internare",
  "patologie",
  "citologie",
  "genetică",
  "toxicologie",
  "virologie",
  "microbiologie",
  "bacteriologie",
  "parazitologie",
  "epidemiologie",
  "biochimie",
  "biologie moleculară",
  "biotehnologie",
  "farmacocinetică",
  "farmacodinamică",
  "biofarmaceutică",
  "farmacogenomică",
  "farmacovigilență",
  "placebo",
  "dublu orb",
  "randomizat",
  "studiu clinic",
  "protocol",
  "consimțământ informat",
  "boală cronică",
  "boală acută",
  "boli rare",
  "genotip",
  "fenotip",
  "marker tumoral",
  "scanare PET",
  "gamma camera",
  "terapie genică",
  "terapie celulară",
  "celule stem",
  "inginerie tisulară",
  "bioimprimare",
  "biosenzori",
  "nanomedicină",
  "terapie cu protoni",
  "terapie cu particule",
  "terapie țintită",
  "anticorpi monoclonali",
  "imunomodulatoare",
  "citokine",
  "inhibitori de kinază",
  "terapie de substituție",
  "terapie combinată",
  "rezistență la antibiotice",
  "probiotice",
  "prebiotice",
  "microbiom",
  "terapie hormonală",
  "terapie substitutivă",
  "depresie",
  "anxietate",
  "tulburare bipolară",
  "schizofrenie",
  "tulburare obsesiv-compulsivă",
  "tulburare de stres posttraumatic",
  "anorexie",
  "bulimie",
  "demență",
  "insomnie",
  "apnee",
  "narcolepsie",
  "somnambulism",
  "bruxism",
  "anestezie generală",
  "anestezie locală",
  "bloc nervos",
  "analgezie epidurală",
  "anestezie spinală",
  "sedare conștientă",
  "ventilație mecanică",
  "oxigenoterapie",
  "terapie intensivă",
  "unitate de terapie intensivă",
  "urgență medicală",
  "prim ajutor",
  "defibrilator",
  "resuscitare cardiopulmonară",
  "sistem de sănătate",
  "medicină preventivă",
  "medicină de familie",
  "medicină internă",
  "medicină sportivă",
  "medicină de urgență",
  "medicină ocupațională",
  "medicină alternativă",
  "medicină complementară",
  "medicină holistică",
  "medicină tradițională",
  "medicină integrativă",
  "bioetică",
  "deontologie",
  "legislație medicală",
  "confidențialitate",
  "consimțământ",
  "autonomie",
  "justiție",
  "beneficiență",
  "non-maleficiență",
  "dispozitiv medical",
  "imagistică medicală",
  "radiologie",
  "ecografie",
  "scanare CT",
  "scanare RMN",
  "scanare PET",
  "raze X",
  "radioterapie",
  "brahiterapie",
  "teleterapie",
  "teleradiologie",
  "imunohistochimie",
  "citometrie în flux",
  "microscopie electronică",
  "microscopie confocală",
  "microscopie optică",
  "test de sânge",
  "analiză de urină",
  "analiză de scaun",
  "profil lipidic",
  "nivel glicemie",
  "hemoglobină glicată",
  "funcție hepatică",
  "funcție renală",
  "electroliți",
  "niveluri hormonale",
  "test de sarcină",
  "screening neonatal",
  "test genetic",
  "test de paternitate",
  "compatibilitate HLA",
  "transplant de organe",
  "transplant de măduvă osoasă",
  "transplant de celule stem",
  "grefă de piele",
  "reconstrucție chirurgicală",
  "chirurgie plastică",
  "chirurgie estetică",
  "chirurgie reconstructivă",
  "chirurgie laparoscopică",
  "chirurgie robotică",
  "chirurgie bariatrică",
  "chirurgie toracică",
  "chirurgie vasculară",
  "chirurgie cardiovasculară",
  "chirurgie ortopedică",
  "chirurgie pediatrică",
  "chirurgie maxilo-facială",
  "chirurgie dentară",
  "chirurgie orală",
  "chirurgie oftalmologică",
  "chirurgie otorinolaringologică",
  "chirurgie neurologică",
  "chirurgie ginecologică",
  "chirurgie urologică",
  "chirurgie colorectală",
  "chirurgie hepato-bilio-pancreatică",
  "chirurgie endocrină",
  "chirurgie traumatologică",
  "chirurgie de urgență",
  "chirurgie generală",
  "chirurgie oncologică",
  "chirurgie minim invazivă",
  "chirurgie artroscopică",
  "chirurgie artroplastică",
  "protezare articulară",
  "reabilitare postoperatorie",
  "complicații postoperatorii",
  "infecție nosocomială",
  "profilaxie antibiotică",
  "cură chirurgicală",
  "asepsie",
  "antisepsie",
  "dezinfectare",
  "sterilizare echipament",
  "calitatea vieții",
  "managementul durerii",
  "analgezie multimodală",
  "terapie fizică",
  "terapie ocupațională",
  "logopedie",
  "terapie cognitiv-comportamentală",
  "terapie familială",
  "terapie de grup",
  "terapie prin artă",
  "terapie prin muzică",
  "hipnoterapie",
  "biofeedback",
  "terapie prin masaj",
  "terapie prin dans",
  "terapie prin mișcare",
  "terapie prin joc",
  "terapie prin animale",
  "asistență medicală",
  "îngrijire paliativă",
  "hospice",
  "asistență la domiciliu",
  "telemedicină",
  "monitorizare la distanță",
  "consiliere genetică",
  "consiliere nutrițională",
  "educație pentru sănătate",
  "screening de sănătate",
  "control de rutină",
  "evaluare medicală",
  "dosar medical electronic",
  "sistem de gestionare a practicii",
  "sistem de gestionare a pacienților",
  "inteligență artificială în medicină",
  "învățare automată în medicină",
  "big data în sănătate",
  "sănătate digitală",
  "e-sănătate",
  "m-sănătate",
  "aplicații de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori purtabili",
  "telemonitorizare",
  "rețea de sănătate",
  "sistem de informare medicală",
  "cybersecuritate în sănătate",
  "protecția datelor medicale",
  "conformitate GDPR",
  "regulamente de sănătate",
  "reglementare farmaceutică",
  "autorizare de medicamente",
  "studiu clinic",
  "fază de studiu clinic",
  "protocol de studiu",
  "recrutare de pacienți",
  "consimțământ informat",
  "placebo",
  "dublu orb",
  "randomizare",
  "blinding",
  "grup de control",
  "grup experimental",
  "metodologie de studiu",
  "analiză statistică",
  "raport de studiu",
  "publicare de studiu",
  "recenzii peer-review",
  "meta-analiză",
  "analiză sistematică",
  "ghiduri clinice",
  "baze de date medicale",
  "PubMed",
  "Cochrane",
  "embase",
  "clinicaltrials.gov",
  "WHO ICTRP",
  "rețea de cunoștințe medicale",
  "educație medicală continuă",
  "licențiere medicală",
  "recertificare",
  "simpozioane medicale",
  "congrese medicale",
  "workshopuri medicale",
  "webinarii medicale",
  "publicații medicale",
  "jurnale medicale",
  "revizuiri de literatură",
  "rapoarte de caz",
  "studii de caz",
  "ghiduri de practică",
  "programe de sănătate publică",
  "campanii de sănătate",
  "promovarea sănătății",
  "prevenirea bolilor",
  "screening de masă",
  "vaccinare în masă",
  "programe de imunizare",
  "controlul bolilor infecțioase",
  "controlul bolilor cronice",
  "managementul bolilor cronice",
  "supravegherea bolilor",
  "monitorizarea epidemiologică",
  "planuri de intervenție în urgență",
  "managementul dezastrelor",
  "asistență umanitară",
  "ajutor medical de urgență",
  "campanii de conștientizare",
  "educație sanitară",
  "programe de nutriție",
  "programe de activitate fizică",
  "promovarea sănătății mintale",
  "prevenirea suicidului",
  "programe anti-fumat",
  "programe anti-drog",
  "programe anti-alcool",
  "programe de prevenire a obezității",
  "programe de sănătate sexuală",
  "programe de sănătate reproductivă",
  "programe de sănătate maternă",
  "programe de sănătate infantilă",
  "sănătatea adolescenților",
  "sănătatea vârstnicilor",
  "sănătatea muncitorilor",
  "sănătatea migranților",
  "sănătatea refugiaților",
  "sănătatea comunităților defavorizate",
  "sănătatea rurală",
  "sănătatea urbană",
  "determinante sociale ale sănătății",
  "inechități în sănătate",
  "acces la servicii de sănătate",
  "calitatea îngrijirii",
  "satisfacția pacienților",
  "implicarea pacienților",
  "drepturile pacienților",
  "siguranța pacienților",
  "experiența pacienților",
  "feedback-ul pacienților",
  "educația pacienților",
  "comunicarea cu pacienții",
  "empatie",
  "relația medic-pacient",
  "comunicarea în îngrijiri de sănătate",
  "comunicarea medicală",
  "barieră lingvistică",
  "traducere medicală",
  "interpretare medicală",
  "alfabetizare în sănătate",
  "educația pentru sănătate",
  "informare medicală",
  "informare în sănătate",
  "tehnologia informației în sănătate",
  "sisteme de sănătate",
  "politici de sănătate",
  "managementul sănătății",
  "finanțarea sănătății",
  "economia sănătății",
  "evaluarea tehnologiilor medicale",
  "planificarea sănătății",
  "dezvoltarea resurselor umane în sănătate",
  "managementul spitalelor",
  "managementul clinicilor",
  "managementul cabinetelor medicale",
  "eficiența sistemului de sănătate",
  "costurile sănătății",
  "accesibilitatea serviciilor de sănătate",
  "echitatea în sănătate",
  "programe de sănătate",
  "servicii de sănătate primară",
  "servicii de sănătate secundară",
  "servicii de sănătate terțiară",
  "îngrijiri integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "telemedicină",
  "sănătate electronică",
  "dosar medical electronic",
  "interoperabilitate",
  "securitatea datelor medicale",
  "protecția confidențialității",
  "reglementări GDPR",
  "compliance medicală",
  "etică medicală",
  "reglementare medicală",
  "practică medicală",
  "standarde medicale",
  "acreditare medicală",
  "controlul calității în sănătate",
  "evaluarea performanței",
  "îmbunătățirea calității",
  "managementul riscului",
  "audit medical",
  "benchmarking în sănătate",
  "inovație în sănătate",
  "cercetare medicală",
  "parteneriate public-privat",
  "finanțare publică",
  "finanțare privată",
  "asigurare de sănătate",
  "sistem de asigurări de sănătate",
  "fonduri de sănătate",
  "plăți din buzunar",
  "cheltuieli pentru sănătate",
  "investiții în sănătate",
  "cost-eficacitate",
  "analiză cost-beneficiu",
  "bugetare în sănătate",
  "politici de sănătate publică",
  "legislație în sănătate",
  "drepturile pacienților",
  "protecția consumatorilor de sănătate",
  "reglementări de sănătate publică",
  "programe guvernamentale de sănătate",
  "organizații internaționale de sănătate",
  "Organizația Mondială a Sănătății",
  "ONU",
  "Unicef",
  "Banca Mondială",
  "organizații non-guvernamentale în sănătate",
  "fundatii de sănătate",
  "campanii de sănătate",
  "educație sanitară",
  "cercetare epidemiologică",
  "programe de prevenție",
  "strategii de sănătate",
  "planuri de acțiune în sănătate",
  "reforme în sănătate",
  "îmbunătățirea accesului la sănătate",
  "servicii de urgență",
  "servicii de ambulanță",
  "servicii de sănătate mentale",
  "servicii de sănătate materno-infantilă",
  "servicii de sănătate a adolescenților",
  "servicii de sănătate a vârstnicilor",
  "servicii de sănătate a muncitorilor",
  "servicii de sănătate pentru refugiați",
  "servicii de sănătate pentru migranți",
  "servicii de sănătate pentru comunități defavorizate",
  "inițiative de sănătate",
  "programe de sănătate ale comunității",
  "educația sanitară a comunității",
  "implicarea comunității în sănătate",
  "voluntariat în sănătate",
  "parteneriate pentru sănătate",
  "cooperare internațională în sănătate",
  "dezvoltare durabilă",
  "sănătate și mediu",
  "poluare și sănătate",
  "climă și sănătate",
  "sănătate urbană",
  "sănătate rurală",
  "sănătate globală",
  "determinante sociale ale sănătății",
  "inechități în sănătate",
  "disparități în sănătate",
  "acces echitabil la sănătate",
  "calitatea îngrijirilor de sănătate",
  "managementul calității în sănătate",
  "programe de certificare în sănătate",
  "standardizare în sănătate",
  "reglementare a produselor medicale",
  "reglementare a dispozitivelor medicale",
  "reglementare a medicamentelor",
  "reglementare a tratamentelor",
  "reglementare a procedurilor medicale",
  "etichete de sănătate",
  "informații pentru pacienți",
  "instrucțiuni de utilizare a medicamentelor",
  "instrucțiuni de utilizare a dispozitivelor medicale",
  "sfaturi pentru pacienți",
  "ghiduri pentru pacienți",
  "educație pentru auto-îngrijire",
  "programe de suport pentru pacienți",
  "grupuri de suport pentru pacienți",
  "rețele de suport pentru pacienți",
  "resurse pentru pacienți",
  "accesibilitate pentru pacienți cu dizabilități",
  "servicii pentru pacienți cu dizabilități",
  "adaptarea serviciilor pentru pacienți cu dizabilități",
  "inovație în îngrijirea pacienților",
  "tehnologii asistive",
  "telemedicină pentru pacienți cu dizabilități",
  "îngrijire personalizată",
  "medicină de precizie",
  "genomică în îngrijire",
  "farmacogenomică în îngrijire",
  "analiză de date în sănătate",
  "big data în sănătate",
  "inteligență artificială în sănătate",
  "algoritmi de sănătate",
  "aplicații mobile pentru sănătate",
  "aplicații mobile pentru pacienți",
  "dispozitive purtabile pentru sănătate",
  "telemonitorizare pentru pacienți",
  "monitorizare la domiciliu",
  "dispozitive medicale inteligente",
  "senzori de sănătate",
  "sisteme de informare în sănătate",
  "sisteme de management al sănătății",
  "platforme de sănătate",
  "ecosisteme de sănătate",
  "rețele de sănătate",
  "parteneriate în sănătate",
  "parteneriate public-private în sănătate",
  "finanțare a sănătății",
  "investiții în sănătate",
  "programe de sănătate finanțate",
  "inițiative de sănătate",
  "proiecte de sănătate",
  "granturi pentru sănătate",
  "subvenții pentru sănătate",
  "burse de sănătate",
  "programe de sănătate la nivel național",
  "programe de sănătate la nivel regional",
  "programe de sănătate la nivel local",
  "programe de sănătate globală",
  "programe de sănătate publică",
  "strategii de sănătate publică",
  "politici de sănătate publică",
  "reglementări de sănătate publică",
  "norme de sănătate publică",
  "standarde de sănătate publică",
  "controlul bolilor infecțioase",
  "prevenirea bolilor infecțioase",
  "monitorizarea bolilor infecțioase",
  "programe de imunizare",
  "vaccinare",
  "campanii de vaccinare",
  "logistică de vaccinare",
  "distribuția vaccinurilor",
  "stocarea vaccinurilor",
  "lanțul de frig",
  "accesibilitate la vaccinuri",
  "acceptarea vaccinurilor",
  "educația pentru vaccinare",
  "comunicarea despre vaccinuri",
  "încrederea în vaccinuri",
  "managementul crizelor de sănătate",
  "răspunsul la urgențe de sănătate",
  "planuri de intervenție în sănătate",
  "managementul dezastrelor în sănătate",
  "pregătirea pentru dezastre în sănătate",
  "resiliența sistemelor de sănătate",
  "refacerea sistemelor de sănătate",
  "infrastructură de sănătate",
  "facilități de sănătate",
  "echipamente medicale",
  "dispozitive medicale",
  "tehnologie medicală",
  "inovație medicală",
  "cercetare medicală",
  "dezvoltare medicală",
  "parteneriate de cercetare",
  "parteneriate de dezvoltare",
  "granturi de cercetare",
  "programe de cercetare",
  "studiu clinic",
  "studiu observațional",
  "metodologie de cercetare",
  "protocol de cercetare",
  "etică în cercetare",
  "consimțământ informat în cercetare",
  "comitet de etică",
  "comitet de evaluare",
  "raport de cercetare",
  "publicare de cercetare",
  "recenzia de cercetare",
  "recenzori peer-review",
  "indexare în baze de date",
  "vizibilitate academică",
  "impact academic",
  "metrici de impact",
  "factori de impact",
  "citări academice",
  "indice h",
  "indice g",
  "indice i10",
  "analiză de citări",
  "rețele academice",
  "parteneriate academice",
  "consorții academice",
  "colaborare academică",
  "inovare academică",
  "transfer de tehnologie",
  "brevete medicale",
  "licențiere medicală",
  "comercializare medicală",
  "întreprinderi medicale",
  "start-up-uri medicale",
  "incubatoare medicale",
  "acceleratoare medicale",
  "investiții în start-up-uri medicale",
  "capital de risc în sănătate",
  "finanțare angel",
  "crowdfunding în sănătate",
  "parteneriate de finanțare",
  "alianțe strategice în sănătate",
  "fuziuni și achiziții în sănătate",
  "dezvoltare de afaceri în sănătate",
  "marketing medical",
  "branding medical",
  "comunicare medicală",
  "relații publice medicale",
  "publicitate medicală",
  "campanii de sănătate",
  "educație pentru sănătate",
  "promovarea sănătății",
  "comportamente sănătoase",
  "stiluri de viață sănătoase",
  "prevenția bolilor",
  "intervenții în sănătate publică",
  "strategii de sănătate",
  "planuri de acțiune în sănătate",
  "obiective de sănătate",
  "indicatori de sănătate",
  "evaluarea sănătății",
  "monitorizarea sănătății",
  "rapoarte de sănătate",
  "studiu de sănătate",
  "analize de sănătate",
  "sistem de date de sănătate",
  "informații de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi în sănătate",
  "tehnologie de sănătate",
  "inovație în sănătate",
  "tehnologii emergente în sănătate",
  "progrese în sănătate",
  "descoperiri în sănătate",
  "progrese medicale",
  "tehnologii de frontieră în sănătate",
  "dispozitive de sănătate de ultimă generație",
  "biotehnologie",
  "nanotehnologie în sănătate",
  "materiale avansate în sănătate",
  "robotică medicală",
  "inginerie genetică",
  "inginerie tisulară",
  "medicină regenerativă",
  "terapie genică",
  "terapie celulară",
  "terapie personalizată",
  "medicină de precizie",
  "genomică",
  "proteomică",
  "metabolomică",
  "bioinformatică",
  "sănătate digitală",
  "sănătate conectată",
  "ecosistem de sănătate",
  "platforme de sănătate",
  "aplicații mobile de sănătate",
  "telemedicină",
  "dispozitive purtabile",
  "senzori de sănătate",
  "monitorizare la distanță",
  "managementul bolilor cronice",
  "supravegherea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "tehnologii de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția datelor de sănătate",
  "reglementări de sănătate digitală",
  "conformitate GDPR",
  "etică în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "inegalități în sănătate",
  "echitatea în sănătate",
  "accesul la îngrijiri de sănătate",
  "servicii de sănătate echitabile",
  "programe de sănătate accesibile",
  "îmbunătățirea accesului la sănătate",
  "servicii de sănătate integrate",
  "îngrijiri centrate pe pacient",
  "îngrijiri coordonate",
  "îngrijiri interdisciplinare",
  "îngrijiri continue",
  "îngrijiri paliative",
  "îngrijiri la domiciliu",
  "telemedicină",
  "telemonitorizare",
  "e-sănătate",
  "m-sănătate",
  "aplicații mobile de sănătate",
  "dispozitive purtabile de sănătate",
  "biosenzori",
  "sisteme de sănătate integrate",
  "platforme de sănătate conectate",
  "ecosisteme de sănătate digitale",
  "inteligență artificială în sănătate",
  "învățare automată în sănătate",
  "algoritmi de sănătate",
  "big data în sănătate",
  "analiză de date în sănătate",
  "predicție și prevenție",
  "decizii bazate pe date",
  "managementul sănătății populației",
  "gestionarea bolilor cronice",
  "monitorizarea sănătății",
  "dosar medical electronic",
  "sisteme de gestionare a sănătății",
  "interoperabilitate",
  "securitatea datelor de sănătate",
  "protecția confidențialității",
  "reglementări GDPR",
  "conformitate în sănătate digitală",
  "cybersecuritate în sănătate",
  "asigurarea calității în sănătate digitală",
  "evaluarea riscurilor",
  "testare și validare",
  "inovare și scalare",
  "parteneriate în sănătate digitală",
  "consorții de sănătate digitală",
  "dezvoltare de produse de sănătate",
  "managementul ciclului de viață al produselor de sănătate",
  "strategii de intrare pe piață",
  "reglementare și aprobare",
  "strategii de marketing în sănătate",
  "comunicare și educație în sănătate",
  "relații cu investitorii",
  "fuziuni și achiziții în sănătate digitală",
  "model de afaceri în sănătate",
  "valorificarea inovației în sănătate",
  "creșterea și extinderea afacerilor în sănătate",
  "managementul performanței",
  "evaluarea impactului",
  "managementul calității",
  "gestionarea schimbării",
  "cultură organizațională în sănătate",
  "leadership în sănătate",
  "strategii de resurse umane",
  "dezvoltarea talentului",
  "formare și educație continuă",
  "managementul echipelor",
  "colaborare interdisciplinară",
  "managementul cunoștințelor",
  "încurajarea inovației",
  "consolidarea capacității",
  "crearea de valoare în sănătate",
  "impact social",
  "responsabilitate socială în sănătate",
  "sustenabilitate în sănătate",
  "dezvoltare durabilă în sănătate",
  "ecologie și sănătate",
  "sănătatea mediului",
  "sănătatea populației",
  "determinantele sociale ale sănătății",
  "durere de cap",
  "durere articulara",
  "durere",
  "durere dinti",
  "durere dentara",
  "somn",
  "somnolenta",
  "apnee",
  "nu pot dormi",
  "nu pot sa dorm",
];

const isMedicalQuery = (query) => {
  return medicalKeywords.some((keyword) =>
    query.toLowerCase().includes(keyword)
  );
};

export async function POST(req) {
  const apiKey = OPENAI_API_KEY;

  if (!apiKey) {
    return new Response(
      JSON.stringify({ error: "OpenAI API key not configured" }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }

  const config = new Configuration({
    apiKey: apiKey,
  });
  const openai = new OpenAIApi(config);

  try {
    const { messages } = await req.json();
    const userMessage = messages[messages.length - 1].content;

    if (!isMedicalQuery(userMessage)) {
      return new Response(
        JSON.stringify({
          role: "assistant",
          content:
            "Imi pare rau, dar sunt asistent virtual care nu are alte cunostinte decat medicale sau farmaceutice. Va rog sa-mi adresati strict doar intrebari din domeniul medical sau farmaceutic. Multumesc!",
          id: generateId(),
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }
      );
    }

    const response = await openai.createChatCompletion({
      model: "gpt-4o",
      stream: true,
      messages: [
        {
          role: "system",
          content: `Ești asistentul AI pentru lanțul de farmacii Apotheka din România. Numele tău este ApothekaAI.
          
          Personalitate și Ton:
          - Ai o personalitate prietenoasă, empatică și profesională.
          - Folosești un ton cald și încurajator, menținând în același timp profesionalismul specific domeniului medical.
          - Încurajezi întotdeauna un stil de viață sănătos și oferi sfaturi în acest sens când este posibil.
          
          Cunoștințe Specializate:
          - Ai informații detaliate despre toate produsele și serviciile oferite de Apotheka.
          - Cunoști regulamentele locale de sănătate și le respecți în recomandările tale.
          - Ești la curent cu promoțiile curente și programele de fidelitate Apotheka.
          
          Restricții și Focalizare:
          - Răspunzi exclusiv în limba română. Nu folosești emoticoane!
          - Te concentrezi doar pe subiecte legate de Apotheka, produse farmaceutice, sănătate și stil de viață sănătos.
          - Pentru orice întrebare în afara acestor domenii, explici politicos că poți ajuta doar cu informații legate de farmacie și sănătate.
          
          Sfaturi Personalizate și Recomandări de Medicamente:
          - Oferă sfaturi personalizate bazate pe informațiile de sănătate ale pacientului, dacă sunt disponibile.
          - Când recomanzi medicamente, include întotdeauna următoarele informații:
            1. Numele medicamentului și scopul său
            2. Doza minimă recomandată, specificând că aceasta poate varia în funcție de individ
            3. Posibile efecte secundare, în special cele care pot afecta capacitatea de a conduce vehicule
            4. O avertizare clară că pacientul ar trebui să consulte un medic sau un farmacist Apotheka înainte de a începe orice tratament
          - Promovează un stil de viață sănătos, oferind sugestii adaptate situației fiecărui client.
          
          Siguranță și Etică:
          - Prioritizează întotdeauna siguranța pacientului.
          - Subliniază importanța consultării unui medic pentru diagnostice sau schimbări în tratament.
          - Menționează în fiecare recomandare de medicament că un farmacist Apotheka poate oferi informații mai detaliate și personalizate.
          - Respectă confidențialitatea datelor pacienților.
          
          Încheiere:
          - Încheie fiecare interacțiune cu expresia "Vă mai pot ajuta cu ceva? Nu ezitați să cereți sfatul unui farmacist Apotheka pentru informații mai detaliate și personalizate."
          
          Important:
          - Oferă întotdeauna cele mai bune sfaturi posibile, bazate pe informațiile medicale actuale și pe practici farmaceutice etice.
          - Fii pregătit să oferi alternative naturale sau suplimente atunci când este cazul, dar întotdeauna în contextul siguranței și eficacității demonstrate.
          - Încurajează prevenția și educația în sănătate ca parte integrantă a fiecărei interacțiuni.`,
        },
        ...messages,
      ],
    });

    const stream = OpenAIStream(response);

    return new StreamingTextResponse(stream);
  } catch (error) {
    console.error("Error in chat route:", error);
    return new Response(
      JSON.stringify({ error: "An error occurred during your request." }),
      {
        status: 500,
        headers: { "Content-Type": "application/json" },
      }
    );
  }
}
